✅ 제너레이터 에러 처리
* 제너레이터에서는 에러는 `안(선언부), 밖(호출부)으로 모두 전달이 된다.`
* `선언부에서 에러 처리를 해 두는것이 좋지만`, 그렇지 않을 경우를 대비해 `밖에서도 try ...catch로 처리해 두는 것이 좋다.`
  ```javascript
  function* gen() {
    try {
      foo(); // next() 호출시 에러 발생
    } catch (e) {
      console.error('[Inner] ERROR :::::::: ', e); // [Inner] ERROR ::::::::  ReferenceError: foo is not defined
    }
  }

  const iter = gen();
  iter.next();
  ```
* 만일 gen에서 에러 처리가 안되었다면? 밖에서도 에러를 다룰 수 있다.
  ```javascript
  function* gen() {
    foo();
  }

  try {
    const iter = gen();
    iter.next();
  } catch (e) {
    console.error('[Outer] -------- ', e); // [Outer] --------  ReferenceError: foo is not defined
  }
  ```